AWSTemplateFormatVersion: '2010-09-09'
Description: CloudShirt Data Tier - RDS (REQ-04)

Parameters:
  VpcId:
    Type: String
  PrivateSubnet1Id:
    Type: String
  PrivateSubnet2Id:
    Type: String
  DBUsername:
    Type: String
    NoEcho: true
  DBPassword:
    Type: String
    NoEcho: true

Resources:
  RdsSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnets for RDS
      SubnetIds:
        - !Ref PrivateSubnet1Id
        - !Ref PrivateSubnet2Id

  RdsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow DB access from VPC (demo)
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 1433
          ToPort: 1433
          CidrIp: 10.0.0.0/16

  CloudShirtDb:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: sqlserver-ex    # demo; kies engine die bij CloudShirt hoort
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBSubnetGroupName: !Ref RdsSubnetGroup
      VPCSecurityGroups:
        - !Ref RdsSecurityGroup
      MultiAZ: true
      PubliclyAccessible: false

Outputs:
  RdsEndpoint:
    Value: !GetAtt CloudShirtDb.Endpoint.Address
    Description: RDS endpoint
